config/routes.rb
Rails.application.routes.draw do
  #devise_for :non_profits
  #devise_for :users
  #Still need to set a root route for Devise
  root 'non_profits#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories, :users, :non_profits
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, allow_nil: false, allow_blank: false
  has_and_belongs_to_many :non_profits
end

app/models/non_profit.rb
class NonProfit < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, allow_nil: false, allow_blank: false
  validates :encrypted_password, presence: true, allow_nil: false, allow_blank: false
  has_and_belongs_to_many :users
  has_and_belongs_to_many :categories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :first_name, presence: true, allow_nil: false, allow_blank: false
  validates :last_name, presence: true, allow_nil: false, allow_blank: false
  validates :email, presence: true, allow_nil: false, allow_blank: false
  validates :encrypted_password, presence: true, allow_nil: false, allow_blank: false
  has_and_belongs_to_many :non_profits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  ##I will want to reserve this route/#action for the Admin (me)
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category Successfully Added"
      redirect_to categories_path
    else
      flash[:notice] = "Something happened, Let's try that again."
      render :new
    end
  end

  ##I will want to reserve this route/#action for the Admin (me)
  def edit
    @category = Category.find(params[:id])
  end

  ##I will want to reserve this route/#action for the Admin (me)
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category successfully updated"
      redirect_to category_path(@category)
    else
      flash[:notice] = "That didn't work, let's do that again."
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private
  def category_params()
    params.require(:category).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/non_profits_controller.rb
class NonProfitsController < ApplicationController
  def index
    @non_profits = NonProfit.all
  end

  def show
    @non_profit = NonProfit.find(params[:id])
  end

  def new
    @non_profit = NonProfit.new
  end

  ##I will want to reserve this route/#action for the Admin (me)
  def create
    @non_profit = NonProfit.new(non_profit_params)
    if @non_profit.save
      flash[:notice] = "Non Profit Successfully Added"
      redirect_to non_profits_path
    else
      flash[:notice] = "Something happened, Let's try that again."
      render :new
    end
  end

  ##I will want to reserve this route/#action for the Admin (me)
  def edit
    @non_profit = NonProfit.find(params[:id])
  end

  ##I will want to reserve this route/#action for the Admin (me)
  def update
    @non_profit = NonProfit.find(params[:id])
    if @non_profit.update(non_profit_params)
      flash[:notice] = "NonProfit successfully updated"
      redirect_to non_profit_path(@non_profit)
    else
      flash[:notice] = "That didn't work, let's do that again."
      render :edit
    end
  end

  def destroy
    @non_profit = NonProfit.find(params[:id])
    @non_profit.destroy
    redirect_to non_profits_path
  end

  private
  def non_profit_params()
    params.require(:non_profit).permit(:name, :email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  ##I will want to reserve this route/#action for the Admin (me)
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User successfully Added"
      redirect_to users_path
    else
      flash[:notice] = "Something happened, Let's try that again."
      render :new
    end
  end

  ##I will want to reserve this route/#action for the Admin (me)
  def edit
    @user = User.find(params[:id])
  end

  ##I will want to reserve this route/#action for the Admin (me)
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User successfully updated"
      redirect_to user_path(@user)
    else
      flash[:notice] = "That didn't work, let's do that again."
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
  def user_params()
    params.require(:user).permit(:first_name, :last_name, :email, :password, :age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/non_profits_helper.rb
module NonProfitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= render "layouts/errors", :object => @category %>

<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/categories/edit.html.erb
<h1>Non profits by category</h1>
<h2>Edit this category</h2>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Browse our non profits by category</h1>

<% if @categories.any? %>
  <ul>
    <% @categories.each do |category| %>
      <li><%= link_to category.name, category_path(category) %></li>
    <% end %>
  </ul>
<% else %>
  <p>
    No categories at this time
  </p>
<% end %>

<p>
  <%= link_to "Back to all non profits", non_profits_path %>
</p>
<p>
  <%= link_to "Add a new Category", new_category_path %>
</p>

app/views/categories/new.html.erb
<h2>Add a non profit category</h2>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<% if @category.non_profits.any? %>
<ul>
  <% @category.non_profits.each do |non_profit| %>
    <li><%= non_profit.name %></li>
  <% end %>
</ul>
<% else %>

<p>
  No non profits in this category currently
</p>

<% end %>

<section>
    <%= link_to "Edit this category", edit_category_path(@category) %>


    <%= link_to "Back to all non profits", non_profits_path %>

    <%= link_to "Back to categories", categories_path %>

</section>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NonProfitRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/non_profits/_form.html.erb
<%= render "layouts/errors", :object => @non_profit %>
<%= form_for @non_profit do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :encrypted_password %>
  <%= f.text_field :encrypted_password %>
  <%= f.submit  %>
<% end %>

app/views/non_profits/edit.html.erb
<h2>Edit this non profit</h2>

<%= render 'form' %>

app/views/non_profits/index.html.erb
<h1>Browse our non profits</h1>

<% if @non_profits.any? %>
  <ul>
    <% @non_profits.each do |non_profit| %>
      <li><%= link_to non_profit.name, non_profit_path(non_profit) %></li>
    <% end %>
  </ul>
<% else %>
  <p>
    No non profits at this time
  </p>
<% end %>

<p>
  <%= link_to "Add a new non profit", new_non_profit_path %>
</p>
<p>
  <%= link_to "Browse by category", categories_path %>
</p>

app/views/non_profits/new.html.erb
<h2>Add a new non profit</h2>

<%= render 'form' %>

app/views/non_profits/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/non_profits/show.html.erb
<h1><%= @non_profit.name %></h1>

<section>
  <p>
    <%= link_to "Edit this non profit", edit_non_profit_path(@non_profit) %>
  </p>
  <p>
    <%= link_to "Back to non profits", non_profits_path %>
  </p>
  <p>
    <%= link_to "Back to categories", categories_path %>
  </p>
</section>

app/views/users/_form.html.erb
##<%= render "layouts/errors", :object => @user %>
<%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <%= f.label :age %>
  <%= f.text_field :age %>
  <%= f.submit  %>
<% end %>

app/views/users/edit.html.erb
<h2>Edit your information</h2>

<%= render 'form' %>

app/views/users/new.html.erb
<h2>Sign up</h2>
<h3>Enter your information below</h3>

<%= render 'form' %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1><%= @user.first_name %> <%= @user.last_name %></h1>

<% if @user.non_profits.any? %>
<ul>
  <% @user.non_profits.each do |non_profit| %>
    <li><%= non_profit.name %></li>
  <% end %>
</ul>
<% else %>

<p>
  You don't currently have any non profits
</p>

<% end %>

<section>
  <p>
    <%= link_to "Edit your profile", edit_user_path(@user) %>
  </p>
  <p>
    <%= link_to "Browse all our non profits", non_profits_path %>
  </p>
  <p>
    <%= link_to "Browse non profits by category", categories_path %>
  </p>
</section>